name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTAxZmUxZjYtNTU1NC00NzM4LWE5NTUtODI5NjQzYmJlODExIiwidGVuYW50X2lkIjoiOTk4YTgzNWJjOTYxOWNkZTgyNTlmNmEzZjcxZTAwMWZhZjg1YTU1ODc2ODYyMGIzYWQxNTYyOTJkNTRhYTdjZiIsImludGVybmFsX3NlY3JldCI6Ijg3MGU2MzVkLTkwYzAtNDJlMC1iNWY4LTI0NzE4NjBiZmM1ZSJ9.friKUU-Z3wU0RvFI3Ody7Q2hPJhULQ80-MmLpVp6_IY"
JWT_SECRET = "Praksha@secretkey"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"